Repository cancervariants/therapy-normalization, pull requests merged in 2023-11, with the labels that each got.

#381 style: remove unnecessary noqa: E501
  src/therapy/cli.py
  src/therapy/database.py
  src/therapy/etl/chembl.py
  src/therapy/etl/guidetopharmacology.py
  src/therapy/etl/hemonc.py
  src/therapy/etl/rxnorm.py
  src/therapy/schemas.py
  tests/unit/test_chembl.py
  tests/unit/test_chemidplus.py
  tests/unit/test_disease_indication.py
  tests/unit/test_drugbank.py
  tests/unit/test_drugsatfda.py
  tests/unit/test_hemonc.py
  tests/unit/test_query.py
Labels: priority:low, cleanup

#384 fix: handle hemonc deprecated concept
  src/therapy/etl/hemonc.py
Labels: priority:medium

#388 style: fix ruff settings
  .pre-commit-config.yaml
  pyproject.toml
  src/therapy/__init__.py
  src/therapy/cli.py
  src/therapy/etl/__init__.py
  src/therapy/etl/base.py
  src/therapy/etl/chemidplus.py
  src/therapy/etl/drugbank.py
  src/therapy/etl/drugsatfda.py
  src/therapy/etl/guidetopharmacology.py
  src/therapy/etl/hemonc.py
  src/therapy/etl/ncit.py
  src/therapy/etl/rxnorm.py
  src/therapy/main.py
  src/therapy/schemas.py
  tests/unit/test_database.py
  tests/unit/test_guidetopharmacology.py
  tests/unit/test_ncit.py
  tests/unit/test_query.py
  tests/unit/test_wikidata.py
Labels: priority:low

#389 feat!: use wags-tails for data management
  Pipfile
  README.md
  pyproject.toml
  src/therapy/cli.py
  src/therapy/etl/base.py
  src/therapy/etl/chembl.py
  src/therapy/etl/chemidplus.py
  src/therapy/etl/drugbank.py
  src/therapy/etl/drugsatfda.py
  src/therapy/etl/guidetopharmacology.py
  src/therapy/etl/hemonc.py
  src/therapy/etl/ncit.py
  src/therapy/etl/rxnorm.py
  src/therapy/etl/wikidata.py
  tests/conftest.py
  tests/data/guidetopharmacology/gtop_ligand_id_mapping_2023.2.tsv
  tests/data/guidetopharmacology/gtop_ligands_2023.2.tsv
  tests/scripts/build_chembl_data.py
  tests/scripts/build_chemidplus_data.py
  tests/scripts/build_drugbank_data.py
  tests/scripts/build_drugsatfda_data.py
  tests/scripts/build_gtop_data.py
  tests/scripts/build_hemonc_data.py
  tests/scripts/build_ncit_data.py
  tests/scripts/build_rxnorm_data.py
  tests/unit/test_chembl.py
Labels: priority:low
