Repository cancervariants/therapy-normalization, pull requests merged in 2023-12, with the labels that each got.

#378 feat!: use abstract interface for DB
  pyproject.toml
  src/therapy/__init__.py
  src/therapy/cli.py
  src/therapy/database.py
  src/therapy/database/__init__.py
  src/therapy/database/database.py
  src/therapy/database/dynamodb.py
  src/therapy/etl/__init__.py
  src/therapy/etl/base.py
  src/therapy/etl/chembl.py
  src/therapy/etl/chemidplus.py
  src/therapy/etl/drugbank.py
  src/therapy/etl/drugsatfda.py
  src/therapy/etl/guidetopharmacology.py
  src/therapy/etl/hemonc.py
  src/therapy/etl/merge.py
  src/therapy/etl/ncit.py
  src/therapy/etl/rxnorm.py
  src/therapy/etl/wikidata.py
  src/therapy/main.py
  src/therapy/query.py
  src/therapy/schemas.py
  tests/conftest.py
  tests/data/disease_normalization.json
  tests/scripts/build_chembl_data.py
  tests/scripts/build_chemidplus_data.py
  tests/scripts/build_disease_normalizer_data.py
  tests/scripts/build_drugbank_data.py
  tests/scripts/build_drugsatfda_data.py
  tests/scripts/build_gtop_data.py
  tests/scripts/build_hemonc_data.py
  tests/scripts/build_ncit_data.py
  tests/scripts/build_rxnorm_data.py
  tests/unit/test_database.py
  tests/unit/test_disease_indication.py
  tests/unit/test_drugbank.py
  tests/unit/test_emit_warnings.py
  tests/unit/test_guidetopharmacology.py
  tests/unit/test_hemonc.py
  tests/unit/test_merge.py
  tests/unit/test_ncit.py
  tests/unit/test_query.py
  tests/unit/test_rxnorm.py
Labels: priority:low

#392 feat!: refine schemas
  README.md
  src/therapy/database/database.py
  src/therapy/database/dynamodb.py
  src/therapy/etl/base.py
  src/therapy/etl/guidetopharmacology.py
  src/therapy/etl/wikidata.py
  src/therapy/main.py
  src/therapy/query.py
  src/therapy/schemas.py
  tests/conftest.py
  tests/unit/test_chembl.py
  tests/unit/test_chemidplus.py
  tests/unit/test_drugbank.py
  tests/unit/test_drugsatfda.py
  tests/unit/test_guidetopharmacology.py
  tests/unit/test_hemonc.py
  tests/unit/test_ncit.py
  tests/unit/test_query.py
  tests/unit/test_rxnorm.py
  tests/unit/test_wikidata.py
Labels: priority:low

#398 feat: set silent to False in CLI
  src/therapy/cli.py
  src/therapy/version.py
Labels: priority:medium, enhancement

#397 docs: update hemonc instructions in readme
  README.md
Labels: priority:low, documentation
