Repository cancervariants/therapy-normalization, pull requests merged in 2023-01, with the labels that each got.

#320 refactor: remove unused ID prefixes
  therapy/etl/ncit.py
  therapy/schemas.py
Labels: priority:low

#319 feat: use new RxNorm download method
  therapy/etl/rxnorm.py
Labels: priority:low

#318 refactor: remove unused classes/imports
  therapy/schemas.py
Labels: priority:low

#316 fix: resolve dependency and environment management issues
  Pipfile
  requirements-dev.txt
  requirements.txt
  setup.cfg
  therapy/cli.py
  therapy/database.py
  therapy/version.py
Labels: priority:low

#329 fix(rxnorm): remove NOCODE id's
  therapy/etl/rxnorm.py
Labels: priority:low

#332 feat: use new RxNorm download method
  therapy/etl/rxnorm.py
Labels: priority:low

#331 refactor: remove unused schema elements
  therapy/etl/ncit.py
  therapy/schemas.py
Labels: priority:low

#328 ci: resolve GH Actions version warnings
  .github/workflows/release.yml
Labels: priority:low

#327 feat: add manual data extraction override rules
  setup.cfg
  tests/unit/test_wikidata.py
  therapy/etl/base.py
  therapy/etl/rules.csv
  therapy/etl/rules.py
Labels: priority:low

#330 fix(gtop): handle guide to pharmacology data updates
  README.md
  tests/data/guidetopharmacology/guidetopharmacology_ligand_id_mapping_2021.4.tsv
  tests/data/guidetopharmacology/guidetopharmacology_ligand_id_mapping_2022.4.tsv
  tests/data/guidetopharmacology/guidetopharmacology_ligands_2021.4.tsv
  tests/data/guidetopharmacology/guidetopharmacology_ligands_2022.4.tsv
  tests/scripts/build_gtop_data.py
  tests/unit/test_guidetopharmacology.py
  therapy/etl/base.py
  therapy/etl/guidetopharmacology.py
Labels: priority:low

#337 fix: pypi package should include all files in etl/ (staging)
  setup.cfg
Labels: priority:medium, bug

#336 fix: pypi package should include all files in etl/
  setup.cfg
  therapy/version.py
Labels: priority:medium, bug

#338 build: update disease normalizer to >=0.3.1
  Pipfile
  requirements-dev.txt
  requirements.txt
  setup.cfg
Labels: build, priority:medium

#339 build: update disease normalizer to ~0.2.19
  Pipfile
  requirements-dev.txt
  requirements.txt
  setup.cfg
Labels: build, priority:medium

#341 fix: Add test for DiseaseIndicationBase
  .github/workflows/checks.yaml
  tests/conftest.py
  tests/scripts/build_disease_normalizer_data.py
  tests/unit/test_disease_indication.py
  therapy/etl/base.py
  therapy/version.py
Labels: priority:medium, bug, test

#342 test: Add test for DiseaseIndicationBase
  .github/workflows/checks.yaml
  tests/conftest.py
  tests/scripts/build_disease_normalizer_data.py
  tests/unit/test_disease_indication.py
Labels: priority:low, test
