Repository cancervariants/therapy-normalization, pull requests merged in 2024-12, with the labels that each got.

#447 feat: properly configure logging in cli
  src/therapy/cli.py
  src/therapy/log.py
Labels: priority:low

#451 fix(docs): use correct pypi url
  README.md
Labels: priority:low, bug, documentation

#450 chore!: rename optional dependency
  .github/workflows/checks.yaml
  README.md
  pyproject.toml
Labels: priority:low, chore
