Repository cancervariants/therapy-normalization, pull requests merged in 2025-02, with the labels that each got.

#462 build!: update ga4gh.vrs
  pyproject.toml
  src/therapy/query.py
  src/therapy/schemas.py
  tests/data/fixtures/query_fixtures.json
  tests/unit/test_query.py
Labels: build, priority:high

#463 cicd: update precommit
  .pre-commit-config.yaml
  pyproject.toml
Labels: priority:low

#467 fix: resolve hemonc issues
  src/therapy/etl/hemonc.py
  src/therapy/schemas.py
  tests/data/fixtures/query_fixtures.json
  tests/data/hemonc/hemonc_concepts_2024-03-01.csv
  tests/data/hemonc/hemonc_concepts_2025-01-09.csv
  tests/data/hemonc/hemonc_rels_2024-03-01.csv
  tests/data/hemonc/hemonc_rels_2025-01-09.csv
  tests/data/hemonc/hemonc_synonyms_2025-01-09.csv
  tests/scripts/build_hemonc_data.py
  tests/unit/test_hemonc.py
  tests/unit/test_schemas.py
Labels: priority:medium
